name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Fmt Go code
        run: "[ ! $(task fmt) ]"

      - name: Vet Go code
        run: task vet

      - name: Lint Go code
        uses: golangci/golangci-lint-action@v6.1.0

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Build
        run: task build
